# AWS_ACCESS_KEY_ID = AKIA2VNYJOEVQQ4OL5N7 
# AWS_SECRET_ACCESS_KEY = 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  

aws_access_key = "AKIA2VNYJOEVQQ4OL5N7"
aws_secret_key = "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"