name: Deploy AWS Resources

on:
  push:
    branches:
      - main  # Adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Replace with desired Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Terraform Init
        run: terraform init       # Replace with your S3 bucket and path

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # - name: Terraform Apply
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Adjust conditions as needed
      #   run: terraform apply -auto-approve tfplan
      
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approved

